# Generated by Django 4.2.22 on 2025-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0227_space_ai_default_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='ai_credits_monthly',
            field=models.IntegerField(default=100),
        ),
    ]
